namespace CloudDebugger.Features.Configuration;

public class AppConfigurationModel
{
    /// <summary>
    /// The raw list of all combined app configurations
    /// </summary>
    public List<KeyValuePair<string, string?>> Config { get; set; } = [];

    /// <summary>
    /// The debug view as generated by the configuration sub-system in ASP.NET Core
    /// </summary>
    public string? DebugView { get; set; }

    /// <summary>
    /// List of all the configuration providers
    /// </summary>
    public List<ConfigurationProviderDetails> ConfigProviders { get; set; } = [];
}