@hostname=https://localhost:5001
@hookId=1

# Sample Cloud Events Schema validation requests

# Sample cloud events validation request (Should send a validation request to event grid)
OPTIONS  {{hostname}}/hook{{hookId}} 
CLIENT-IP: 51.12.47.159:65157
DISGUISED-HOST: as-clouddebugger-linux.azurewebsites.net
Max-Forwards: 10
WAS-DEFAULT-HOSTNAME: as-clouddebugger-linux.azurewebsites.net
WebHook-Request-Callback: https://rp-swedencentral.eventgrid.azure.net:553/eventsubscriptions/cloudeventsschemasub/validate?id=96DD3B04-10AB-4527-91A0-37457909A33D&t=2024-10-03T13:47:57.9844984Z&apiVersion=2023-12-15-preview&token=RKIAeiDJjKEa9uu%2bfSZKxh0rC142dOmOwohQtEwmtKY%3d
WebHook-Request-Origin: eventgrid.azure.net
X-ARR-LOG-ID: 7f832876-7361-4d0e-904f-159aa77a5268
X-ARR-SSL: 2048|256|CN=Microsoft Azure RSA TLS Issuing CA 04, O=Microsoft Corporation, C=US|CN=*.azurewebsites.net, O=Microsoft Corporation, L=Redmond, S=WA, C=US
X-AppService-Proto: https
X-Client-IP: 51.12.47.159
X-Client-Port: 65157
X-Forwarded-TlsVersion: 1.2
X-Original-For: [::ffff:169.254.129.1]:34645
X-Original-Proto: http
X-Original-URL: /hook2
X-SITE-DEPLOYMENT-ID: as-CloudDebugger-Linux
X-WAWS-Unencoded-URL: /hook2



### Sample cloud events validation request

OPTIONS {{hostname}}/hook{{hookId}}
Max-Forwards: 10
WebHook-Request-Origin: eventgrid.azure.net
WebHook-Request-Callback: https://rp-swedencentral.eventgrid.azure.net:553/eventsubscriptions/myeventsubscription/validate?id=75EAB6E5-DD6B-49FA-839F-1E6C45698EC0&t=2024-10-01T09:32:09.9335224Z&apiVersion=2023-12-15-preview&token=CnozdXI%2f9iXl00ZT0OIt11L0igEjYQ0CR7mJUo4fN7M%3d
X-ARR-LOG-ID: f880cdcf-ba93-48f3-a585-433cf36d451b
CLIENT-IP: 51.12.47.148:50055
DISGUISED-HOST: as-clouddebugger-windows.azurewebsites.net
X-SITE-DEPLOYMENT-ID: as-CloudDebugger-Windows
WAS-DEFAULT-HOSTNAME: as-clouddebugger-windows.azurewebsites.net
X-Forwarded-Proto: https
X-AppService-Proto: https
X-ARR-SSL: 2048|256|CN=Microsoft Azure RSA TLS Issuing CA 07, O=Microsoft Corporation, C=US|CN=*.azurewebsites.net, O=Microsoft Corporation, L=Redmond, S=WA, C=US
X-Forwarded-TlsVersion: 1.2
X-Forwarded-For: 51.12.47.148:50055
X-Original-URL: /Hook1
X-WAWS-Unencoded-URL: /Hook1



### validation request


OPTIONS {{hostname}}/hook{{hookId}}
Max-Forwards: 10
WAS-DEFAULT-HOSTNAME: as-clouddebugger-linux.azurewebsites.net
WebHook-Request-Callback: https://rp-swedencentral.eventgrid.azure.net:553/eventsubscriptions/blobchanges2/validate?id=234AFE6A-A435-4D81-AC37-7E24F10BD31A&t=2024-08-22T14:06:42.7316312Z&apiVersion=2023-12-15-preview&token=iF2Tdqnmojm0l8DkE%2feAKoV8FUjNk1Kb1QyDn0trQnE%3d
WebHook-Request-Origin: eventgrid.azure.net
X-ARR-LOG-ID: 59d38479-e269-4314-a8c9-48469745e3b3
X-ARR-SSL: 2048|256|CN=Microsoft Azure RSA TLS Issuing CA 04, O=Microsoft Corporation, C=US|CN=*.azurewebsites.net, O=Microsoft Corporation, L=Redmond, S=WA, C=US
X-AppService-Proto: https
X-Client-IP: 51.12.47.155
X-Client-Port: 30343
X-SITE-DEPLOYMENT-ID: as-CloudDebugger-Linux
X-WAWS-Unencoded-URL: /WebhookAdvanced/Hook1



###

#Sample Event Grid Cloud event validation request 
OPTIONS {{hostname}}/hook{{hookId}}
WebHook-Request-Callback: https://rp-swedencentral.eventgrid.azure.net:553/eventsubscriptions/storagechangessubscription/validate?id=4DBEDDCF-0D41-444A-B127-D5C23181F528&t=2024-07-05T12:07:14.7028427Z&apiVersion=2023-12-15-preview&token=HC1QbIN%2fWRwr5TYOINVxpBKTtYHxWvhTbo%2bnRpTG%2fFg%3d
WebHook-Request-Origin: eventgrid.azure.net
x-arr-ssl: true
x-envoy-expected-rq-timeout-ms: 1800000
x-envoy-external-address: 51.12.47.155
x-forwarded-for: 51.12.47.155
x-forwarded-proto: https
x-k8se-app-kind: web
x-k8se-app-name: clouddebugger--69zn5vw
x-k8se-app-namespace: k8se-apps
x-k8se-protocol: http1
x-ms-containerapp-name: clouddebugger
x-ms-containerapp-revision-name: clouddebugger--69zn5vw
x-request-id: 092cfd9a-3ab2-4765-8548-91f86c5ea1df



###

#Sample Event Grid Cloud event validation request to local webhook endpoint https://localhost:5001/hook3
OPTIONS {{hostname}}/hook{{hookId}}
WebHook-Request-Callback: https://localhost:5001/hook3
WebHook-Request-Origin: eventgrid.azure.net
x-arr-ssl: true
x-envoy-expected-rq-timeout-ms: 1800000
x-envoy-external-address: 51.12.47.155
x-forwarded-for: 51.12.47.155
x-forwarded-proto: https
x-k8se-app-kind: web
x-k8se-app-name: clouddebugger--69zn5vw
x-k8se-app-namespace: k8se-apps
x-k8se-protocol: http1
x-ms-containerapp-name: clouddebugger
x-ms-containerapp-revision-name: clouddebugger--69zn5vw
x-request-id: 092cfd9a-3ab2-4765-8548-91f86c5ea1df




###

#Sample Event Grid Cloud event validation request that failed in Azure (Lower-case headers)
OPTIONS {{hostname}}/hook{{hookId}}
Content-Length: 0
webhook-request-callback: https://rp-swedencentral.eventgrid.azure.net:553/eventsubscriptions/cloudevent-linux-container-app/validate?id=DDAD8472-2717-4624-8661-210F29029BB2&t=2025-01-29T18:57:11.1296364Z&apiVersion=2024-12-15-preview&token=%2fnvnFmnrE5MGmBCutflYlZTU1Ux9f7JakOtnRNyyYUQ%3d
webhook-request-origin: eventgrid.azure.net
x-arr-ssl: true
x-envoy-expected-rq-timeout-ms: 1800000
x-envoy-external-address: 51.12.47.151
x-k8se-app-kind: web
x-k8se-app-name: ca-clouddebugger--9bn4egg
x-k8se-app-namespace: k8se-apps
x-k8se-protocol: http1
x-ms-containerapp-name: ca-clouddebugger
x-ms-containerapp-revision-name: ca-clouddebugger--9bn4egg
x-request-id: 796c0195-690a-4aa8-95ba-705655383419