@hostname=https://localhost:5001
@hookId=1

# Sample requests to test the webhook overview page


#Sample cloud event
POST {{hostname}}/hook{{hookId}}
Content-Type: application/cloudevents+json; charset=utf-8
aeg-delivery-count: 0
aeg-event-type: Notification
aeg-metadata-version: 1
aeg-subscription-name: ALLBUSINESSEVENTS
webhook-request-origin: eventgrid.azure.net
x-arr-ssl: true
x-envoy-expected-rq-timeout-ms: 1800000
x-envoy-external-address: 51.12.47.168
x-forwarded-for: 51.12.47.168
x-forwarded-proto: https
x-k8se-app-kind: web
x-k8se-app-name: clouddebugger--9ry8jzw
x-k8se-app-namespace: k8se-apps
x-k8se-protocol: http1
x-ms-containerapp-name: clouddebugger
x-ms-containerapp-revision-name: clouddebugger--9ry8jzw
x-request-id: 59ad7b35-9ba9-4769-b926-ad3c16b38993

{
  "id": "973ed28b-38eb-423e-9e6c-839bb86c648d",
  "source": "CloudDebugger",
  "type": "BusinessEvent.NewOrder",
  "data": {
    "ProductId": 1,
    "ProductName": "Product 1",
    "Color": "Red"
  },
  "time": "2024-07-06T09:31:58.6139464+00:00",
  "specversion": "1.0",
  "subject": "Product1",
  "traceparent": "00-f4671311242f1d91aec83873553bc799-0674a399b6808262-00"
}

###

#Sample cloud event
POST {{hostname}}/hook{{hookId}}
Content-Type: application/cloudevents+json; charset=utf-8
aeg-delivery-count: 0
aeg-event-type: Notification
aeg-metadata-version: 1
aeg-subscription-name: ALLBUSINESSEVENTS
webhook-request-origin: eventgrid.azure.net
x-arr-ssl: true
x-envoy-expected-rq-timeout-ms: 1800000
x-envoy-external-address: 51.12.47.168
x-forwarded-for: 51.12.47.168
x-forwarded-proto: https
x-k8se-app-kind: web
x-k8se-app-name: clouddebugger--9ry8jzw
x-k8se-app-namespace: k8se-apps
x-k8se-protocol: http1
x-ms-containerapp-name: clouddebugger
x-ms-containerapp-revision-name: clouddebugger--9ry8jzw
x-request-id: 59ad7b35-9ba9-4769-b926-ad3c16b38993

{
  "id": "973ed28b-38eb-423e-9e6c-839bb86c648d",
  "source": "CloudDebugger",
  "type": "BusinessEvent.NewOrder",
  "data": {
    "ProductId": 1,
    "ProductName": "Product 1",
    "Color": "Red"
  },
  "time": "2024-07-06T09:31:58.6139464+00:00",
  "specversion": "1.0",
  "subject": "Product1",
  "traceparent": "00-f4671311242f1d91aec83873553bc799-0674a399b6808262-00"
}
