@hostname=https://localhost:5001
@hookId=1

#Sample Event Grid validation request (array)
POST {{hostname}}/hook{{hookId}}
Content-Type: application/json; charset=utf-8
Aeg-Event-Type: SubscriptionValidation

[
  {
    "id": "01a07c63-4614-4839-ab71-d85778996402",
    "topic": "/subscriptions/b78d216b-d714-4664-b39a-26ef8dbcfdf1/resourceGroups/rg-dev/providers/microsoft.storage/storageaccounts/mytndatastorageaccount",
    "subject": "",
    "data": {
      "validationCode": "2C59C8CA-B453-4FB0-9094-4C0DEAA4761A",
      "validationUrl": "https://www.tn-data.se"
    },
    "eventType": "Microsoft.EventGrid.SubscriptionValidationEvent",
    "eventTime": "2024-07-03T12:03:43.1634844Z",
    "metadataVersion": "1",
    "dataVersion": "2"
  }
]

###


#Sample Event Grid validation request (single object)
POST {{hostname}}/hook{{hookId}}
Content-Type: application/json; charset=utf-8
Aeg-Event-Type: SubscriptionValidation

{
  "id": "01a07c63-4614-4839-ab71-d85778996402",
  "topic": "/subscriptions/b78d216b-d714-4664-b39a-26ef8dbcfdf1/resourceGroups/rg-dev/providers/microsoft.storage/storageaccounts/mytndatastorageaccount",
  "subject": "",
  "data": {
    "validationCode": "2C59C8CA-B453-4FB0-9094-4C0DEAA4761A",
    "validationUrl": "https://rp-swedencentral.eventgrid.azure.net:553/eventsubscriptions/blobsadded/validate?id=2C59C8CA-B453-4FB0-9094-4C0DEAA4761A&t=2024-07-03T12:03:43.1634232Z&apiVersion=2023-12-15-preview&token=gEYLdkoR1LChv9wp0DOXIefcvDS23IOkpkT5TBu0xgk%3d"
  },
  "eventType": "Microsoft.EventGrid.SubscriptionValidationEvent",
  "eventTime": "2024-07-03T12:03:43.1634844Z",
  "metadataVersion": "1",
  "dataVersion": "2"
}



###

### Eventgrid validation request
OPTIONS {{hostname}}/hook{{hookId}}
Max-Forwards: 10
WAS-DEFAULT-HOSTNAME: as-clouddebugger-linux.azurewebsites.net
WebHook-Request-Callback: https://rp-swedencentral.eventgrid.azure.net:553/eventsubscriptions/blobchanges2/validate?id=234AFE6A-A435-4D81-AC37-7E24F10BD31A&t=2024-08-22T14:06:42.7316312Z&apiVersion=2023-12-15-preview&token=iF2Tdqnmojm0l8DkE%2feAKoV8FUjNk1Kb1QyDn0trQnE%3d
WebHook-Request-Origin: eventgrid.azure.net
X-ARR-LOG-ID: 59d38479-e269-4314-a8c9-48469745e3b3
X-ARR-SSL: 2048|256|CN=Microsoft Azure RSA TLS Issuing CA 04, O=Microsoft Corporation, C=US|CN=*.azurewebsites.net, O=Microsoft Corporation, L=Redmond, S=WA, C=US
X-AppService-Proto: https
X-Client-IP: 51.12.47.155
X-Client-Port: 30343
X-SITE-DEPLOYMENT-ID: as-CloudDebugger-Linux
X-WAWS-Unencoded-URL: /WebhookAdvanced/Hook1




###

#Sample Event Grid Cloud event validation request 
OPTIONS {{@hostname}}/hook{{hookId}}
webhook-request-callback: https://rp-swedencentral.eventgrid.azure.net:553/eventsubscriptions/storagechangessubscription/validate?id=4DBEDDCF-0D41-444A-B127-D5C23181F528&t=2024-07-05T12:07:14.7028427Z&apiVersion=2023-12-15-preview&token=HC1QbIN%2fWRwr5TYOINVxpBKTtYHxWvhTbo%2bnRpTG%2fFg%3d
webhook-request-origin: eventgrid.azure.net
x-arr-ssl: true
x-envoy-expected-rq-timeout-ms: 1800000
x-envoy-external-address: 51.12.47.155
x-forwarded-for: 51.12.47.155
x-forwarded-proto: https
x-k8se-app-kind: web
x-k8se-app-name: clouddebugger--69zn5vw
x-k8se-app-namespace: k8se-apps
x-k8se-protocol: http1
x-ms-containerapp-name: clouddebugger
x-ms-containerapp-revision-name: clouddebugger--69zn5vw
x-request-id: 092cfd9a-3ab2-4765-8548-91f86c5ea1df

 
### Sample cloud events validation request

OPTIONS {{hostname}}/hook{{hookId}}
Max-Forwards: 10
WebHook-Request-Origin: eventgrid.azure.net
WebHook-Request-Callback: https://rp-swedencentral.eventgrid.azure.net:553/eventsubscriptions/myeventsubscription/validate?id=75EAB6E5-DD6B-49FA-839F-1E6C45698EC0&t=2024-10-01T09:32:09.9335224Z&apiVersion=2023-12-15-preview&token=CnozdXI%2f9iXl00ZT0OIt11L0igEjYQ0CR7mJUo4fN7M%3d
X-ARR-LOG-ID: f880cdcf-ba93-48f3-a585-433cf36d451b
CLIENT-IP: 51.12.47.148:50055
DISGUISED-HOST: as-clouddebugger-windows.azurewebsites.net
X-SITE-DEPLOYMENT-ID: as-CloudDebugger-Windows
WAS-DEFAULT-HOSTNAME: as-clouddebugger-windows.azurewebsites.net
X-Forwarded-Proto: https
X-AppService-Proto: https
X-ARR-SSL: 2048|256|CN=Microsoft Azure RSA TLS Issuing CA 07, O=Microsoft Corporation, C=US|CN=*.azurewebsites.net, O=Microsoft Corporation, L=Redmond, S=WA, C=US
X-Forwarded-TlsVersion: 1.2
X-Forwarded-For: 51.12.47.148:50055
X-Original-URL: /Hook1
X-WAWS-Unencoded-URL: /Hook1

###

# Sample event grid schema validation request (Should send a validation request to event grid)
POST {{hostname}}/hook{{hookId}}
CLIENT-IP: 51.12.47.159:34816
Content-Type: application/json; charset=utf-8
DISGUISED-HOST: as-clouddebugger-linux.azurewebsites.net
Max-Forwards: 10
WAS-DEFAULT-HOSTNAME: as-clouddebugger-linux.azurewebsites.net
X-ARR-LOG-ID: 74054a67-c35f-4af2-953d-947a5d1713f2
X-ARR-SSL: 2048|256|CN=Microsoft Azure RSA TLS Issuing CA 04, O=Microsoft Corporation, C=US|CN=*.azurewebsites.net, O=Microsoft Corporation, L=Redmond, S=WA, C=US
X-AppService-Proto: https
X-Client-IP: 51.12.47.159
X-Client-Port: 34816
X-Forwarded-TlsVersion: 1.2
X-Original-For: [::ffff:169.254.129.1]:53207
X-Original-Proto: http
X-Original-URL: /hook1
X-SITE-DEPLOYMENT-ID: as-CloudDebugger-Linux
X-WAWS-Unencoded-URL: /hook1
aeg-data-version: 1
aeg-delivery-count: 0
aeg-event-type: SubscriptionValidation
aeg-metadata-version: 0
aeg-subscription-name: EVENTGRIDSCHEMASUB

[
  {
    "id": "4ba32c73-7763-4c7c-8baf-6196c25c416c",
    "topic": "/subscriptions/b78d216b-d714-4664-b39a-26ef8dbcfdf1/resourceGroups/rg-CloudDebugger/providers/Microsoft.Storage/storageAccounts/clouddebuggerstorage",
    "subject": "",
    "data": {
      "validationCode": "FC84B66C-7B58-405E-BE24-A87C494A1CC0",
      "validationUrl": "https://rp-swedencentral.eventgrid.azure.net:553/eventsubscriptions/eventgridschemasub/validate?id=FC84B66C-7B58-405E-BE24-A87C494A1CC0&t=2024-10-03T13:43:42.8765034Z&apiVersion=2023-12-15-preview&token=icmN05ebGFuqLPGe5KaOVXAp7C9ls%2bD9amXLGOhuQgs%3d"
    },
    "eventType": "Microsoft.EventGrid.SubscriptionValidationEvent",
    "eventTime": "2024-10-03T13:43:42.8765645Z",
    "metadataVersion": "1",
    "dataVersion": "2"
  }
]

###

# Sample cloud events validation request (Should send a validation request to event grid)
OPTIONS  {{hostname}}/hook{{hookId}} 
CLIENT-IP: 51.12.47.159:65157
DISGUISED-HOST: as-clouddebugger-linux.azurewebsites.net
Host: as-clouddebugger-linux.azurewebsites.net
Max-Forwards: 10
WAS-DEFAULT-HOSTNAME: as-clouddebugger-linux.azurewebsites.net
WebHook-Request-Callback: https://rp-swedencentral.eventgrid.azure.net:553/eventsubscriptions/cloudeventsschemasub/validate?id=96DD3B04-10AB-4527-91A0-37457909A33D&t=2024-10-03T13:47:57.9844984Z&apiVersion=2023-12-15-preview&token=RKIAeiDJjKEa9uu%2bfSZKxh0rC142dOmOwohQtEwmtKY%3d
WebHook-Request-Origin: eventgrid.azure.net
X-ARR-LOG-ID: 7f832876-7361-4d0e-904f-159aa77a5268
X-ARR-SSL: 2048|256|CN=Microsoft Azure RSA TLS Issuing CA 04, O=Microsoft Corporation, C=US|CN=*.azurewebsites.net, O=Microsoft Corporation, L=Redmond, S=WA, C=US
X-AppService-Proto: https
X-Client-IP: 51.12.47.159
X-Client-Port: 65157
X-Forwarded-TlsVersion: 1.2
X-Original-For: [::ffff:169.254.129.1]:34645
X-Original-Proto: http
X-Original-URL: /hook2
X-SITE-DEPLOYMENT-ID: as-CloudDebugger-Linux
X-WAWS-Unencoded-URL: /hook2



